(()=>{
const STORAGE='monsaba-treasure-solver-v1',states=['unknown','miss','hit','found'],labels={unknown:'未確認',miss:'空白',hit:'宝ヒット',found:'発見済み'};
const $=s=>document.querySelector(s);let history=[];let model={size:6,spec:'2x2:1, 1x3:1',cells:Array(36).fill('unknown')};
function parseSpec(text){const shapes=[];for(const part of text.split(',')){const match=part.trim().match(/^(\d+)x(\d+):(\d+)$/i);if(!match)throw new Error(`形式を確認してください: ${part.trim()}`);const [,w,h,count]=match.map(Number);if(w<1||h<1||count<1||w>model.size||h>model.size)throw new Error('宝の形・個数が盤面の範囲外です。');for(let i=0;i<count;i++)shapes.push({w,h,id:`${w}x${h}-${i}`});}if(!shapes.length)throw new Error('宝を1個以上入力してください。');return shapes.sort((a,b)=>b.w*b.h-a.w*a.h)}
function save(){localStorage.setItem(STORAGE,JSON.stringify(model))}function snapshot(){history.push(JSON.stringify(model));if(history.length>40)history.shift()}
function restore(){try{const saved=JSON.parse(localStorage.getItem(STORAGE));if(saved?.size&&Array.isArray(saved.cells)){model=saved;$('#boardSize').value=String(model.size);$('#treasureSpec').value=model.spec}}catch{}}
function build(){const board=$('#board');board.style.setProperty('--board-size',model.size);board.innerHTML='';model.cells.forEach((state,index)=>{const b=document.createElement('button');b.type='button';b.className='treasure-cell';b.dataset.state=state;b.dataset.index=index;b.setAttribute('role','gridcell');b.setAttribute('aria-label',`${Math.floor(index/model.size)+1}行${index%model.size+1}列：${labels[state]}`);b.innerHTML=`<span>${state==='miss'?'×':state==='hit'?'●':state==='found'?'✓':''}</span><small></small>`;b.addEventListener('click',()=>{snapshot();model.cells[index]=states[(states.indexOf(model.cells[index])+1)%states.length];save();build()});board.append(b)})}
function placements(shape){const out=[];for(let y=0;y<=model.size-shape.h;y++)for(let x=0;x<=model.size-shape.w;x++){const cells=[];for(let dy=0;dy<shape.h;dy++)for(let dx=0;dx<shape.w;dx++)cells.push((y+dy)*model.size+x+dx);if(!cells.some(i=>model.cells[i]==='miss'))out.push(cells)}return out}
function solve(){let shapes;try{model.spec=$('#treasureSpec').value.trim();shapes=parseSpec(model.spec)}catch(error){show(error.message,true);return}snapshot();save();const candidates=shapes.map(placements);if(candidates.some(list=>!list.length)){show('入力条件を満たす宝配置がありません。',true);return}const required=new Set(model.cells.flatMap((s,i)=>s==='hit'||s==='found'?[i]:[]));const configurations=[];const cap=20000;function backtrack(depth,used,chosen){if(configurations.length>=cap)return;if(depth===shapes.length){if([...required].every(i=>used.has(i)))configurations.push(chosen.flat());return}for(const p of candidates[depth]){if(p.some(i=>used.has(i)))continue;const next=new Set(used);p.forEach(i=>next.add(i));const remainingCells=candidates.slice(depth+1).flat().flat();if([...required].some(i=>!next.has(i)&&!remainingCells.includes(i)))continue;backtrack(depth+1,next,[...chosen,p])}}backtrack(0,new Set(),[]);if(!configurations.length){show('入力条件と宝の形が矛盾しています。Undoで戻せます。',true);clearProb();return}const tally=Array(model.cells.length).fill(0);configurations.forEach(cells=>new Set(cells).forEach(i=>tally[i]++));let best=-1,bestP=-1;document.querySelectorAll('.treasure-cell').forEach((cell,i)=>{cell.classList.remove('is-best');const small=cell.querySelector('small');if(model.cells[i]==='unknown'){const p=tally[i]/configurations.length;small.textContent=`${Math.round(p*100)}%`;if(p>bestP){bestP=p;best=i}}else small.textContent='' });if(best>=0)document.querySelector(`.treasure-cell[data-index="${best}"]`)?.classList.add('is-best');const remaining=shapes.reduce((sum,s)=>sum+s.w*s.h,0)-model.cells.filter(x=>x==='found').length;const estimate=bestP>0?Math.ceil(remaining/bestP):'—';show(`有効候補 ${configurations.length.toLocaleString()}件${configurations.length>=cap?'（上限までの概算）':''}`,false,`おすすめ：${Math.floor(best/model.size)+1}行${best%model.size+1}列（${Math.round(bestP*100)}%）／残りツルハシ概算 ${estimate}`);window.monsabaTrack?.('event_tool_use',{tool:'treasure_hunt',action:'calculate'})}
function clearProb(){document.querySelectorAll('.treasure-cell').forEach(c=>{c.classList.remove('is-best');c.querySelector('small').textContent=''})}function show(title,error=false,text=''){const box=$('#solverStatus');box.classList.toggle('is-error',error);box.innerHTML=`<strong>${title}</strong><p>${text||'盤面か宝設定を見直してください。'}</p>`}
$('#boardSize').addEventListener('change',e=>{snapshot();model.size=Number(e.target.value);model.cells=Array(model.size*model.size).fill('unknown');save();build();clearProb()});$('#treasureSpec').addEventListener('change',()=>{model.spec=$('#treasureSpec').value.trim();save()});$('#calculate').addEventListener('click',solve);$('#undo').addEventListener('click',()=>{if(!history.length)return;model=JSON.parse(history.pop());$('#boardSize').value=model.size;$('#treasureSpec').value=model.spec;save();build();show('1手戻しました')});$('#reset').addEventListener('click',()=>{snapshot();model.cells=Array(model.size*model.size).fill('unknown');save();build();show('盤面をリセットしました')});restore();build();
})();
