export const COPY = {
  ja: {
    title: 'Tierメーカー', site: 'モンサバ攻略DB', unofficial: '非公式', home: 'トップ', ratings: '攻略DBのTier', team: '編成メーカー',
    intro: '自分のTier表を作ろう。',
    help: 'キャラをドラッグ、または選んでからTierをタップ。配置済みキャラを選ぶと、移動・並び替え・未評価へ戻す操作ができます。各項目は独立して評価できます。',
    local: 'この端末に自動保存', localNote: '評価は端末内だけに保存されます。攻略DBの評価には反映されません。キャラは各系統のT1画像で表示します。',
    roles: { front: '前衛', healer: 'ヒーラー', dps: 'DPS', buff: 'バフ', overall: '総合' },
    tableTitle: '表のタイトル（任意）', placeholder: '好きなタイトルを入力', category: '評価項目', addCategory: '項目を追加',
    rename: '名前変更', remove: '削除', addTier: 'Tierを追加', tierName: 'Tier名', color: 'Tierの色', up: '上へ', down: '下へ',
    unplaced: '未評価', search: 'キャラを検索', searchHint: '進化後の名前でも検索', all: 'すべての属性',
    attributes: { '火': '火', '草': '草', '水': '水', '岩': '岩', '雷': '雷' },
    empty: 'ここへ配置', noResults: '条件に合うキャラがいません。', select: '選択中', cancel: '選択解除', previous: '左へ', next: '右へ', return: '未評価に戻す',
    undo: '元に戻す', redo: 'やり直す', clear: 'すべての配置を解除', reset: '初期状態に戻す',
    clearConfirm: '全項目の配置を解除します。項目名とTier設定は残ります。', resetConfirm: '項目・Tier設定を含め、初期状態に戻します。',
    deleteTier: 'このTierを削除します。配置したキャラは未評価に戻ります。', deleteCategory: 'この評価項目と配置を削除します。ほかの項目は残ります。',
    image: 'この項目を画像保存', export: 'まとめて画像保存', exportTitle: '画像にする項目を選択', includeUnplaced: '未評価キャラを画像に含める',
    save: '保存', close: '閉じる', name: '名前', editName: '名前を入力', newCategory: '新しい評価項目', newTier: '新しいTier',
    saved: '端末に保存しました。', storageError: '端末に保存できません。再読み込み前に画像保存してください。',
    invalidDraft: '保存データを読み込めませんでした。元データは変更していません。次の編集で新しい表を保存します。',
    changedElsewhere: '別のタブでこの表が変更されました。このタブの再読み込みで最新版を読み込めます。',
    loading: 'キャラを読み込み中…', loadError: 'キャラを読み込めませんでした。', retry: '再読み込み',
    exporting: '画像を作成中…', imageSaved: 'PNG画像を作成しました。', exportError: '画像を作成できませんでした。もう一度お試しください。',
    tooLarge: '画像が大きすぎます。保存する項目を減らしてください。', imageMissing: '一部の画像を読み込めません。通信状態を確認して再度お試しください。',
    preview: '画像を開く', download: 'PNGを保存', imageHelp: 'スマホで保存されない場合は画像を開き、長押しで保存してください。',
    footer: 'モンスターサバイバルの非公式ツールです。キャラ画像には運営チーム共有の公式Creator Assets等の確認済み素材を使用しています。',
    personal: '個人作成のTier表', unknown: '現在の一覧にないキャラを保存データに保持しています。',
    exportEmpty: '1つ以上の項目を選んでください。', confirm: '実行する', yes: '確認', limit: '追加上限に達しています。',
    selectedHint: 'Tierの空き部分で末尾に配置。キャラを押すと、その直前に挿入します。'
  },
  en: {
    title: 'Tier Maker', site: 'Monsaba Guide DB', unofficial: 'Unofficial', home: 'Home', ratings: 'Guide tier lists', team: 'Team Builder',
    intro: 'Build your own tier list.',
    help: 'Drag a character, or select one and tap a tier. Select a placed character to move, reorder, or return it to Unrated. Each category has its own ratings.',
    local: 'Auto-saved on this device', localNote: 'Your ratings stay on this device and do not change the guide ratings. Each family uses its T1 image.',
    roles: { front: 'Frontline', healer: 'Healer', dps: 'DPS', buff: 'Buff', overall: 'Overall' },
    tableTitle: 'Table title (optional)', placeholder: 'Enter any title', category: 'Category', addCategory: 'Add category',
    rename: 'Rename', remove: 'Delete', addTier: 'Add tier', tierName: 'Tier name', color: 'Tier color', up: 'Move up', down: 'Move down',
    unplaced: 'Unrated', search: 'Search characters', searchHint: 'Search by any evolution name', all: 'All attributes',
    attributes: { '火': 'Fire', '草': 'Grass', '水': 'Water', '岩': 'Rock', '雷': 'Thunder' },
    empty: 'Place here', noResults: 'No matching characters.', select: 'Selected', cancel: 'Deselect', previous: 'Move left', next: 'Move right', return: 'Return to Unrated',
    undo: 'Undo', redo: 'Redo', clear: 'Clear all placements', reset: 'Restore defaults',
    clearConfirm: 'Clear placements in every category? Category names and tier settings will stay.', resetConfirm: 'Restore the initial categories, tiers, and placements?',
    deleteTier: 'Delete this tier? Its characters will return to Unrated.', deleteCategory: 'Delete this category and its placements? Other categories will stay.',
    image: 'Save this category as image', export: 'Save combined image', exportTitle: 'Choose categories for the image', includeUnplaced: 'Include unrated characters',
    save: 'Save', close: 'Close', name: 'Name', editName: 'Enter a name', newCategory: 'New category', newTier: 'New tier',
    saved: 'Saved on this device.', storageError: 'Could not save on this device. Save an image before reloading.',
    invalidDraft: 'Could not read the saved draft. It has not been changed. Your next edit will save a new table.',
    changedElsewhere: 'Another tab changed this table. Reload this tab to load the latest version.',
    loading: 'Loading characters…', loadError: 'Could not load characters.', retry: 'Reload',
    exporting: 'Creating image…', imageSaved: 'PNG image created.', exportError: 'Could not create the image. Please try again.',
    tooLarge: 'This image is too large. Choose fewer categories.', imageMissing: 'Some character images could not load. Check your connection and try again.',
    preview: 'Open image', download: 'Save PNG', imageHelp: 'If your phone does not save the file, open the image and press and hold it to save.',
    footer: 'Unofficial Monster Survival tool. Character images use verified materials including official Creator Assets shared by the game team.',
    personal: 'Personal tier list', unknown: 'Characters missing from the current catalog are retained in your saved draft.',
    exportEmpty: 'Choose at least one category.', confirm: 'Confirm', yes: 'Confirm', limit: 'The limit has been reached.',
    selectedHint: 'Tap an empty part of a tier to append. Tap a character to insert before it.'
  },
  'zh-CN': {
    title: 'Tier制作器', site: '怪物生存攻略DB', unofficial: '非官方', home: '首页', ratings: '攻略DB评价', team: '阵容制作器',
    intro: '制作自己的Tier表。',
    help: '拖动角色，或先选择角色再点击Tier。选择已放置角色可移动、排序或移回未评价。各评价项目独立。',
    local: '自动保存在此设备', localNote: '个人评价仅保存在此设备，不会更改攻略DB的评价。各系列使用T1图片。',
    roles: { front: '前卫', healer: '治疗', dps: 'DPS', buff: '增益', overall: '综合' },
    tableTitle: '表格标题（可选）', placeholder: '输入任意标题', category: '评价项目', addCategory: '添加项目',
    rename: '重命名', remove: '删除', addTier: '添加Tier', tierName: 'Tier名称', color: 'Tier颜色', up: '上移', down: '下移',
    unplaced: '未评价', search: '搜索角色', searchHint: '也可搜索进化后的名称', all: '全部属性',
    attributes: { '火': '火', '草': '草', '水': '水', '岩': '岩', '雷': '雷' },
    empty: '放置到此处', noResults: '没有匹配的角色。', select: '已选择', cancel: '取消选择', previous: '左移', next: '右移', return: '移回未评价',
    undo: '撤销', redo: '重做', clear: '清空所有放置', reset: '恢复初始状态',
    clearConfirm: '清空全部项目中的角色放置？保留项目名称与Tier设置。', resetConfirm: '将项目、Tier设置与角色放置恢复到初始状态？',
    deleteTier: '删除此Tier？其中的角色会移回未评价。', deleteCategory: '删除此评价项目及其角色放置？其他项目会保留。',
    image: '保存此项目图片', export: '保存合并图片', exportTitle: '选择要保存的评价项目', includeUnplaced: '在图片中包含未评价角色',
    save: '保存', close: '关闭', name: '名称', editName: '输入名称', newCategory: '新评价项目', newTier: '新Tier',
    saved: '已保存在此设备。', storageError: '无法保存在此设备。重新加载前请先保存图片。',
    invalidDraft: '无法读取保存的表格，原数据未改动。下次编辑将保存新表格。',
    changedElsewhere: '另一个标签页更改了此表格。重新加载此页可读取最新版本。',
    loading: '正在加载角色…', loadError: '无法加载角色。', retry: '重新加载',
    exporting: '正在生成图片…', imageSaved: '已生成PNG图片。', exportError: '无法生成图片，请重试。',
    tooLarge: '图片过大，请减少所选项目。', imageMissing: '部分角色图片加载失败，请检查网络后重试。',
    preview: '打开图片', download: '保存PNG', imageHelp: '手机未保存时，请打开图片并长按保存。',
    footer: '本工具为怪物生存非官方工具。角色图片使用已确认素材，包括游戏运营团队分享的官方Creator Assets。',
    personal: '个人Tier表', unknown: '保存数据保留了当前列表中不存在的角色。',
    exportEmpty: '请至少选择一个项目。', confirm: '确认执行', yes: '确认', limit: '已达到添加上限。',
    selectedHint: '点击Tier空白处添加到末尾；点击角色则插入其前方。'
  }
};
