import { createHash, createHmac, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { decodeTeam, encodeTeam, playerCount, playerLimit, TEAM_SLOTS } from '../team-builder/team-core.js';

export const COMMUNITY_TAGS = Object.freeze(['初心者向け', '安定重視', '火力重視', '耐久重視', '低育成', '高育成', 'T4少なめ', 'オート', '手動', '検証中']);
export const COMMUNITY_RESULTS = Object.freeze(['untested', 'challenging', 'round', 'cleared']);
export const COMMUNITY_REPORT_REASONS = Object.freeze(['荒らし', '誹謗中傷', 'スパム', '個人情報', '不適切内容', 'その他']);
export const COMMUNITY_CONFIG = Object.freeze({ pageSize: 10, maxScan: 200, maxBodyBytes: 20 * 1024, maxTitle: 80, maxNote: 300, maxName: 30, maxComment: 500, publishCooldown: 180, publishHourlyMax: 5, actionHourlyMax: 40, reportDailyMax: 20 });

export class CommunityError extends Error {
  constructor(code, message, status = 400) { super(message); this.name = 'CommunityError'; this.code = code; this.status = status; }
}

const sha256 = (value) => createHash('sha256').update(String(value)).digest('hex');
const chars = (value) => [...value].length;
function text(value, label, max, { required = false, line = false } = {}) {
  if (value === undefined || value === null) value = '';
  if (typeof value !== 'string') throw new CommunityError('INVALID_FIELD', `${label}の形式が正しくありません。`);
  let result = value.normalize('NFKC').replace(/\r\n?/g, '\n').trim();
  if (line) result = result.replace(/\s+/gu, ' ');
  if (required && !result) throw new CommunityError('REQUIRED_FIELD', `${label}を入力してください。`);
  if (chars(result) > max) throw new CommunityError('TOO_LONG', `${label}は${max}文字以内で入力してください。`);
  if (/[<>\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(result)) throw new CommunityError('UNSAFE_TEXT', `${label}に使用できない文字が含まれています。`);
  return result;
}
function object(body) { if (!body || typeof body !== 'object' || Array.isArray(body)) throw new CommunityError('INVALID_JSON', '送信内容の形式が正しくありません。'); if (body.website) throw new CommunityError('SPAM_DETECTED', '投稿を受け付けられませんでした。'); }
function integer(value, label, min, max) { const number = Number(value); if (!Number.isInteger(number) || number < min || number > max) throw new CommunityError('INVALID_FIELD', `${label}が正しくありません。`); return number; }
function cursor(value) { if (!value) return 0; try { const parsed = Number(Buffer.from(String(value), 'base64url').toString()); if (!Number.isSafeInteger(parsed) || parsed < 0) throw new Error(); return parsed; } catch { throw new CommunityError('INVALID_CURSOR', '一覧の続き位置が正しくありません。'); } }
const encodeCursor = (value) => Buffer.from(String(value)).toString('base64url');
function safeEqual(left, right) { if (!left || !right || typeof left !== 'string' || typeof right !== 'string') return false; return timingSafeEqual(Buffer.from(sha256(left), 'hex'), Buffer.from(sha256(right), 'hex')); }
function authorize(record, supplied, admin, configuredAdmin) { if (safeEqual(admin, configuredAdmin)) return; if (!supplied) throw new CommunityError('OWNER_TOKEN_REQUIRED', '投稿者情報がありません。', 401); if (!safeEqual(sha256(supplied), record.ownerTokenHash)) throw new CommunityError('OWNER_TOKEN_INVALID', 'この投稿を操作する権限がありません。', 403); }
const publicBuild = ({ ownerTokenHash, ipHash, status, ...build }) => build;
const publicComment = ({ ownerTokenHash, ipHash, status, ...comment }) => comment;

export function createCommunityService({ store, families, chips, seasons, ipHashSecret, adminToken, now = () => Date.now(), uuid = () => randomUUID(), ownerToken = () => randomBytes(32).toString('base64url') }) {
  if (!store || !families?.length || !chips?.length || !seasons?.length || !ipHashSecret || !adminToken) throw new CommunityError('SERVICE_UNAVAILABLE', '現在、みんなの編成を利用できません。', 503);
  const seasonMap = new Map(seasons.map((season) => [season.id, season]));
  const validChipIds = new Set(chips.map((chip) => chip.id));
  const hashIp = (ip) => createHmac('sha256', ipHashSecret).update(String(ip || 'unknown')).digest('hex');
  const rate = async (kind, hash) => { const rules = kind === 'publish' ? [[`${kind}:short:${hash}`, COMMUNITY_CONFIG.publishCooldown, 1], [`${kind}:hour:${hash}`, 3600, COMMUNITY_CONFIG.publishHourlyMax]] : [[`${kind}:hour:${hash}`, 3600, kind === 'report' ? COMMUNITY_CONFIG.reportDailyMax : COMMUNITY_CONFIG.actionHourlyMax]]; for (const [key, seconds, max] of rules) if (await store.incrementRateLimit(key, seconds) > max) throw new CommunityError('RATE_LIMITED', '連続操作が多いため、時間を空けてお試しください。', 429); };
  const validateFormation = (code) => { const formationCode = text(code, '編成', 8192, { required: true, line: true }); let team; try { team = decodeTeam(formationCode, families, chips); } catch { throw new CommunityError('INVALID_FORMATION', '編成データを読み込めません。'); } if (team.mode !== 'zombie' || team.slots.length !== TEAM_SLOTS || !team.slots.some(Boolean)) throw new CommunityError('INVALID_FORMATION', 'タタを配置したゾンビラッシュ編成だけ投稿できます。'); for (const playerId of [1, 2]) { if (playerCount(team, playerId) > playerLimit(team, playerId)) throw new CommunityError('INVALID_FORMATION', 'Playerの配置上限を超えています。'); if (team.chips[playerId].length > 3 || team.chips[playerId].some((id) => !validChipIds.has(id))) throw new CommunityError('INVALID_FORMATION', 'チップ構成が正しくありません。'); } return { formationCode: encodeTeam(team, families, chips), team }; };
  const validateMeta = (body, { partial = false } = {}) => { object(body); const seasonId = text(body.seasonId, 'Season', 48, { required: !partial, line: true }); const season = seasonId ? seasonMap.get(seasonId) : null; if (seasonId && !season) throw new CommunityError('INVALID_SEASON', 'Seasonが正しくありません。'); const difficulty = body.difficulty === undefined && partial ? undefined : integer(body.difficulty, '難易度', 1, season?.maximumDifficulty || 4); const resultStatus = body.resultStatus === undefined && partial ? undefined : text(body.resultStatus, '結果', 20, { required: true, line: true }); if (resultStatus !== undefined && !COMMUNITY_RESULTS.includes(resultStatus)) throw new CommunityError('INVALID_RESULT', '結果が正しくありません。'); let highestRound = body.highestRound === undefined && partial ? undefined : integer(body.highestRound ?? 0, '最高Round', 0, season?.roundsPerGame || 25); if (resultStatus === 'cleared') highestRound = season.roundsPerGame; const tags = body.tags === undefined && partial ? undefined : [...new Set(Array.isArray(body.tags) ? body.tags : [])]; if (tags && (tags.length > 5 || tags.some((tag) => !COMMUNITY_TAGS.includes(tag)))) throw new CommunityError('INVALID_TAG', 'タグが正しくありません。'); return { seasonId, difficulty, resultStatus, highestRound, tags }; };

  return {
    async list(params = {}) { const offset = cursor(params.cursor); const sort = ['new', 'helpful', 'trials', 'clears', 'round'].includes(params.sort) ? params.sort : 'new'; const filters = { seasonId: text(params.seasonId, 'Season', 48, { line: true }), difficulty: params.difficulty ? integer(params.difficulty, '難易度', 1, 4) : null, resultStatus: text(params.resultStatus, '結果', 20, { line: true }), tag: text(params.tag, 'タグ', 24, { line: true }) }; if (filters.resultStatus && !COMMUNITY_RESULTS.includes(filters.resultStatus)) throw new CommunityError('INVALID_RESULT', '結果が正しくありません。'); if (filters.tag && !COMMUNITY_TAGS.includes(filters.tag)) throw new CommunityError('INVALID_TAG', 'タグが正しくありません。'); const result = await store.listBuilds({ offset, limit: COMMUNITY_CONFIG.pageSize, scanLimit: COMMUNITY_CONFIG.maxScan, sort, ...filters }); return { builds: result.builds.filter((item) => item?.status === 'active').map(publicBuild), nextCursor: result.hasMore ? encodeCursor(offset + result.consumed) : null }; },
    async get(id, commentCursor = '') { const build = await store.getBuild(text(id, '投稿ID', 80, { required: true, line: true })); if (!build || build.status !== 'active') throw new CommunityError('BUILD_NOT_FOUND', '編成投稿が見つかりません。', 404); const offset = cursor(commentCursor); const result = await store.listComments(build.id, { offset, limit: 20 }); return { build: publicBuild(build), comments: result.comments.filter((item) => item?.status === 'active').map(publicComment), nextCursor: result.hasMore ? encodeCursor(offset + result.consumed) : null }; },
    async create(body, ip) { const meta = validateMeta(body); const { formationCode, team } = validateFormation(body.formationCode); const input = { title: text(body.title, 'タイトル', COMMUNITY_CONFIG.maxTitle, { required: true, line: true }), note: text(body.note, '補足', COMMUNITY_CONFIG.maxNote), authorDisplayName: text(body.authorDisplayName, '投稿者名', COMMUNITY_CONFIG.maxName, { line: true }) || '匿名トレーナー', ...meta }; const ipHash = hashIp(ip); await rate('publish', ipHash); if (!(await store.reserveDuplicate(ipHash, sha256(formationCode), 86400))) throw new CommunityError('DUPLICATE_FORMATION', '同じ編成は時間を空けて投稿してください。', 409); const token = ownerToken(); const stamp = new Date(now()).toISOString(); const build = { id: uuid(), ...input, formationCode, playerCounts: { 1: playerCount(team, 1), 2: playerCount(team, 2) }, createdAt: stamp, updatedAt: stamp, helpfulCount: 0, trialCount: 0, clearReportCount: 0, commentCount: 0, reportedBestRound: input.highestRound, sourceType: 'community_user', moderationStatus: 'visible', status: 'active', ownerTokenHash: sha256(token) }; await store.createBuild(build); return { build: publicBuild(build), ownerToken: token }; },
    async edit(body, admin = '') { object(body); const id = text(body.id, '投稿ID', 80, { required: true, line: true }); const existing = await store.getBuild(id); if (!existing || existing.status !== 'active') throw new CommunityError('BUILD_NOT_FOUND', '編成投稿が見つかりません。', 404); authorize(existing, body.ownerToken, admin, adminToken); const meta = validateMeta(body); const { formationCode, team } = validateFormation(body.formationCode); const updated = { ...existing, title: text(body.title, 'タイトル', COMMUNITY_CONFIG.maxTitle, { required: true, line: true }), note: text(body.note, '補足', COMMUNITY_CONFIG.maxNote), authorDisplayName: text(body.authorDisplayName, '投稿者名', COMMUNITY_CONFIG.maxName, { line: true }) || '匿名トレーナー', ...meta, formationCode, playerCounts: { 1: playerCount(team, 1), 2: playerCount(team, 2) }, updatedAt: new Date(now()).toISOString() }; await store.updateBuild(updated); return { build: publicBuild(updated) }; },
    async remove(body, admin = '') { object(body); const id = text(body.id, '投稿ID', 80, { required: true, line: true }); const existing = await store.getBuild(id); if (!existing || existing.status !== 'active') throw new CommunityError('BUILD_NOT_FOUND', '編成投稿が見つかりません。', 404); authorize(existing, body.ownerToken, admin, adminToken); await store.removeBuild(id); return { removed: true }; },
    async helpful(body, ip) { object(body); const id = text(body.id, '投稿ID', 80, { required: true, line: true }); const build = await store.getBuild(id); if (!build || build.status !== 'active') throw new CommunityError('BUILD_NOT_FOUND', '編成投稿が見つかりません。', 404); const hash = hashIp(ip); await rate('helpful', hash); if (!(await store.reserveAction('helpful', hash, id, 365 * 86400))) throw new CommunityError('ALREADY_RECORDED', 'すでに記録済みです。', 409); const updated = { ...build, helpfulCount: build.helpfulCount + 1 }; await store.updateBuild(updated); return { helpfulCount: updated.helpfulCount }; },
    async trial(body, ip) { const meta = validateMeta(body); object(body); const id = text(body.id, '投稿ID', 80, { required: true, line: true }); const build = await store.getBuild(id); if (!build || build.status !== 'active') throw new CommunityError('BUILD_NOT_FOUND', '編成投稿が見つかりません。', 404); const hash = hashIp(ip); await rate('trial', hash); const stamp = new Date(now()).toISOString(); const trial = { id: uuid(), buildId: id, seasonId: meta.seasonId, difficulty: meta.difficulty, highestRound: meta.highestRound, cleared: meta.resultStatus === 'cleared', changed: body.changed === true, comment: text(body.comment, 'コメント', 200), createdAt: stamp, sourceType: 'community_user' }; await store.createTrial(trial); const updated = { ...build, trialCount: build.trialCount + 1, clearReportCount: build.clearReportCount + (trial.cleared ? 1 : 0), reportedBestRound: Math.max(build.reportedBestRound || 0, trial.highestRound) }; await store.updateBuild(updated); return { trial, summary: { trialCount: updated.trialCount, clearReportCount: updated.clearReportCount, reportedBestRound: updated.reportedBestRound } }; },
    async comment(body, ip) { object(body); const buildId = text(body.id, '投稿ID', 80, { required: true, line: true }); const build = await store.getBuild(buildId); if (!build || build.status !== 'active') throw new CommunityError('BUILD_NOT_FOUND', '編成投稿が見つかりません。', 404); const parentCommentId = text(body.parentCommentId, '返信先', 80, { line: true }) || null; if (parentCommentId) { const parent = await store.getComment(parentCommentId); if (!parent || parent.buildId !== buildId || parent.status !== 'active') throw new CommunityError('INVALID_PARENT', '返信先が正しくありません。'); } const hash = hashIp(ip); await rate('comment', hash); const token = ownerToken(); const comment = { id: uuid(), buildId, parentCommentId, name: text(body.name, '名前', COMMUNITY_CONFIG.maxName, { line: true }) || '匿名', content: text(body.content, 'コメント', COMMUNITY_CONFIG.maxComment, { required: true }), createdAt: new Date(now()).toISOString(), sourceType: 'community_user', status: 'active', ownerTokenHash: sha256(token) }; await store.createComment(comment); await store.updateBuild({ ...build, commentCount: build.commentCount + 1 }); return { comment: publicComment(comment), ownerToken: token }; },
    async report(body, ip) { object(body); const targetType = text(body.targetType, '対象', 20, { required: true, line: true }); const targetId = text(body.targetId, '対象ID', 80, { required: true, line: true }); const reason = text(body.reason, '理由', 20, { required: true, line: true }); if (!['build', 'comment'].includes(targetType) || !COMMUNITY_REPORT_REASONS.includes(reason)) throw new CommunityError('INVALID_REPORT', '通報内容が正しくありません。'); const hash = hashIp(ip); await rate('report', hash); if (!(await store.reserveAction('report', hash, `${targetType}:${targetId}`, 86400))) throw new CommunityError('ALREADY_REPORTED', 'すでに通報済みです。', 409); const report = { id: uuid(), targetType, targetId, reason, createdAt: new Date(now()).toISOString(), sourceType: 'community_user', status: 'open' }; await store.createReport(report, 180 * 86400); return { report: { id: report.id, targetType, targetId, reason, createdAt: report.createdAt } }; }
  };
}
